language: php

php:
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install

script: 
  - vendor/bin/grumphp run
  - vendor/bin/phpunit --coverage-text